before_script:
    - sleep 15
    - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
services:
    - mongodb
language: node_js
node_js: 
    - lts/*
cache: npm
install:
    - npm ci
script:
    - npm test