services:
    - mongodb
language: node_js
node_js:
    - lts/*
stages:
    - name: test
jobs:
    include:
        - stage: test
        script:
            - npm test
            - npm run coverage-codecov
        name: test:mocha
        cache: npm
        install:
        - npm install -g
        - mongod --dbpath=data/db &
        - sleep 20